### PR TITLE
Support multiple physical devices (#153)

### PR DESCRIPTION
**Pull request by mrhill**
Echo appears to identify Hue devices by their dictionary index returned from the
/api/api/lights endpoint. Espalexa enumerated devices starting at 1,
and returns that as the device key. So if multiple ESPs are running Espalexa,
the devices clash on their index key.

Instead construct a unique device key as signed 32-bit int using:
- bit 0..6  7-bit Espalexa device index
- bit 7..30 bottom 3 bytes of MAC address
- bit 31    0

### CODE REVIEW

**Review by pcb1962 — COMMENTED** [review]
I have tested this change and can confirm that it fixes an issue where multiple physical Espalexa devices were being confused when placed into alexa groups.

**Comment by Edding300** [comment]
After i've postet my issue  #153 i got it working somehow, but now i have the problem for your solution. But what do i have to do? Where do i have to change something? 
Thanks.

**Comment by barneyz** [comment]
Please Aircookie can you merge it to the master release. I reviewed and tested this change and can also confirm that it fixes an issue where multiple physical Espalexa devices.

For discussion: I am a little afraid when using only 3 bytes from mac address that there were two or more devices in the house with the same 3 mac bytes (and one or more of the not used mac bytes are different). When i order 10 esp32-devices, i dont know it is possible they have ongoing mac adresses differ only in one byte?  In fauxmoesp-lib it seems they recently hashed also the device name into the unique id and unique device key.....

**Comment by Aircoookie** [comment]
Thank you very much for the pull request and please apologize my lack of communication.
This is perfect, thank you also for the affirmations that it works fine, which I can confirm with Echo 2 and Dot 3!

@barneyz The unique ID being based on the last 3 bytes of the MAC is good enough for now I'd say. 16M different IDs do make an overlap possible, but it is very unlikely. Any hash function would compress down to 3 bytes as well (due to max. length of the device ID being 4 byte and needing 1 byte for Espalexa device #), making an overlap just as (un)likely as when using the raw bytes from the MAC. The first bytes of the MAC often match though with other units from the same batch, so it is definitely a good idea to use the last bytes.

**Pull request merged**
